const ANSWERS = [
    'LUNCH', 'PAINT', 'CRANE', 'BREAD', 'SHOCK', 'PLANT', 'GHOST', 'BRAVE', 'ROUND', 'SWEET',
    'MUSIC', 'SWEAR', 'PILOT', 'SIGHT', 'HEART', 'BLOCK', 'CLOUD', 'GRACE', 'TRAIN', 'BRICK',
    'BLINK', 'CURLY', 'FROST', 'GRAIN', 'QUIET', 'CROWN', 'STORM', 'BRAND', 'CLOUD', 'FABLE',
    'SHIFT', 'TOWER', 'WATER', 'BRAVE', 'PIXEL', 'FOUND', 'BOSSY', 'NIGHT', 'HONEY', 'COVER',
    'TREND', 'SMART', 'THINK', 'ALIGN', 'ROBIN', 'BRISK', 'FIBER', 'MIGHT', 'SHAKE', 'RHYME'
];
